import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

import "../styles/globals.css"
import { cn } from "@/lib/utils"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="ja">
			<body
				className={cn(
					`${geistSans.variable} ${geistMono.variable}`,
					"min-h-dvh h-dvh bg-background text-foreground overscroll-none antialiased"
				)}
			>
				{children}
			</body>
		</html>
	)
}
