/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Sample API
 * 適当なサンプルOpenAPI定義
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateUserRequest
} from '../models/createUserRequest';

import type {
  User
} from '../models/user';


/**
 * @summary ユーザー一覧取得
 */
export type getUsersResponse200 = {
  data: User[]
  status: 200
}
    
export type getUsersResponseSuccess = (getUsersResponse200) & {
  headers: Headers;
};
;

export type getUsersResponse = (getUsersResponseSuccess)

export const getGetUsersUrl = () => {


  

  return `http://localhost:4010/users`
}

export const getUsers = async ( options?: RequestInit): Promise<getUsersResponse> => {
  
  const res = await fetch(getGetUsersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUsersResponse
}


/**
 * @summary ユーザー作成
 */
export type postUsersResponse201 = {
  data: User
  status: 201
}
    
export type postUsersResponseSuccess = (postUsersResponse201) & {
  headers: Headers;
};
;

export type postUsersResponse = (postUsersResponseSuccess)

export const getPostUsersUrl = () => {


  

  return `http://localhost:4010/users`
}

export const postUsers = async (createUserRequest: CreateUserRequest, options?: RequestInit): Promise<postUsersResponse> => {
  
  const res = await fetch(getPostUsersUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createUserRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postUsersResponse
}


/**
 * @summary ユーザー取得
 */
export type getUsersUserIdResponse200 = {
  data: User
  status: 200
}

export type getUsersUserIdResponse404 = {
  data: void
  status: 404
}
    
export type getUsersUserIdResponseSuccess = (getUsersUserIdResponse200) & {
  headers: Headers;
};
export type getUsersUserIdResponseError = (getUsersUserIdResponse404) & {
  headers: Headers;
};

export type getUsersUserIdResponse = (getUsersUserIdResponseSuccess | getUsersUserIdResponseError)

export const getGetUsersUserIdUrl = (userId: string,) => {


  

  return `http://localhost:4010/users/${userId}`
}

export const getUsersUserId = async (userId: string, options?: RequestInit): Promise<getUsersUserIdResponse> => {
  
  const res = await fetch(getGetUsersUserIdUrl(userId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUsersUserIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUsersUserIdResponse
}


