/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Sample API
 * 適当なサンプルOpenAPI定義
 * OpenAPI spec version: 1.0.0
 */

export interface CreateUserRequest {
  name: string;
  email: string;
}
